name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ---------------------------------------------------------
      # CHECKOUT REPO
      # ---------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # ---------------------------------------------------------
      # INSTALL CML (pour rapport)
      # ---------------------------------------------------------
      - name: Setup CML
        uses: iterative/setup-cml@v2

      # ---------------------------------------------------------
      # INSTALL DEPENDENCIES
      # ---------------------------------------------------------
      - name: Install dependencies
        run: make install

      # ---------------------------------------------------------
      # FORMAT CODE
      # ---------------------------------------------------------
      - name: Format
        run: make format

      # ---------------------------------------------------------
      # TRAIN MODEL
      # ---------------------------------------------------------
      - name: Train model
        run: make train

      # ---------------------------------------------------------
      # EVALUATION + CML REPORT
      # ---------------------------------------------------------
      - name: Evaluation and CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make eval

      # ---------------------------------------------------------
      # UPDATE BRANCH (COMMIT AUTOMATIQUE)
      # ---------------------------------------------------------
      - name: Update Branch
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          NAME: ${{ secrets.USER_NAME }}
          EMAIL: ${{ secrets.USER_EMAIL }}
        run: make update-branch USER_NAME=$NAME USER_EMAIL=$EMAIL

      # ---------------------------------------------------------
      # DEPLOYMENT TO HUGGING FACE SPACE
      # ---------------------------------------------------------
      - name: Deployment To Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install "huggingface_hub[cli]"

          # Login to HF
          huggingface-cli login --token $HF_TOKEN

          echo "ðŸ“¤ Uploading Model folder..."
          huggingface-cli upload Abdelouafi/iris-classification-cicd \
            ./Model /Model \
            --repo-type=space \
            --commit-message "Sync Model"

          echo "ðŸ“¤ Uploading Results/Metrics..."
          huggingface-cli upload Abdelouafi/iris-classification-cicd \
            ./Results /Results \
            --repo-type=space \
            --commit-message "Sync Metrics"

          echo "ðŸ“¤ Uploading App files..."
          huggingface-cli upload Abdelouafi/iris-classification-cicd \
            ./App /App \
            --repo-type=space \
            --commit-message "Sync App"

          echo "ðŸš€ Deployment complete!"
